spring: 
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: zuul
      profile: dev
    rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin   
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
---
spring:
  profiles: eureka1

server:
  port: 2001
  
# eureka1 Ïò eureka2 ×¢²á
eureka:
  instance:
    hostname: eureka1
  client:
    service-url: 
      defaultZone: http://eureka2:2002/eureka

---
spring:
  profiles: eureka2

server:
  port: 2002